<?xml version="1.0" encoding="utf-8"?><Database Name="JGD" Class="CompanyDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\MSSQLSERVER2;Initial Catalog=JGD;User ID=sa;MultipleActiveResultSets=True" SettingsObjectName="SK.Entities.Properties.Settings" SettingsPropertyName="JGDConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Company" Member="Company">
    <Type Name="Company">
      <Column Name="ID" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Contact" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Tel" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Member="Mobile" Type="System.String" CanBeNull="false" />
      <Column Member="Password" Type="System.String" CanBeNull="false" />
      <Column Member="IsPass" Type="System.Boolean" CanBeNull="false" />
      <Column Member="CreateAt" Type="System.DateTime" CanBeNull="false" />
      <Column Member="UpdateAt" Type="System.DateTime" CanBeNull="false" />
    </Type>
  </Table>
</Database>