<?xml version="1.0" encoding="utf-8"?><Database Name="JGD" Class="ProcessingOrderDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\MSSQLSERVER2;Initial Catalog=JGD;User ID=sa;MultipleActiveResultSets=True" SettingsObjectName="SK.Entities.Properties.Settings" SettingsPropertyName="JGDConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ProcessingOrder" Member="ProcessingOrder">
    <Type Name="ProcessingOrder">
      <Column Name="ID" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OrderNo" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="CreateAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="OrderStatus" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UpdateAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DelType" Type="DeliveryType" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PickType" Type="SK.Entities.ProcessingOrder.PickUpType" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pic" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
</Database>