<?xml version="1.0" encoding="utf-8"?><Database Name="JGD" Class="WXUserDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\MSSQLSERVER2;Initial Catalog=JGD;User ID=sa;MultipleActiveResultSets=True" SettingsObjectName="SK.Entities.Properties.Settings" SettingsPropertyName="JGDConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.WXUser" Member="WXUser">
    <Type Name="WXUser">
      <Column Name="openid" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nickname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sex" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="province" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="city" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="country" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="headimgurl" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="privilege" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="unionid" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Member="createtime" Type="System.DateTime" CanBeNull="false" />
    </Type>
  </Table>
</Database>